import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getSortedPostsData } from '../lib/posts'

export default function Home({allPostsData}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className={styles.main}>
        <h1 className={styles.title}>
         Read {' '} 
         <Link href="/posts/first-post">
           <a>this page!</a> 
         </Link>
        </h1>
        <a href="/posts/first-post" className={styles.don}>Goto this page</a>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <ul>
        {  allPostsData.map(({id , date , title})=> (
            <li key={id}>
              {title} <br />
              {id} <br />
              {date} <br />
            </li>
          ))}
          </ul>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}